-- СОЗДАНИЕ ТАБЛИЦЫ ОТЗЫВОВ (REVIEWS)

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- ID пользователя (из таблицы clients)
    product_id BIGINT REFERENCES "Products"(id) ON DELETE CASCADE, -- Ссылка на товар (Учитываем, что ID товара теперь BIGINT)
    rating INTEGER CHECK (rating >= 1 AND rating <= 5), -- Оценка от 1 до 5
    comment TEXT, -- Сам текст отзыва
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Включаем RLS (защиту), но разрешаем всем читать и писать (пока MVP)
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
ON reviews FOR SELECT
USING (true);

CREATE POLICY "Enable insert access for all users"
ON reviews FOR INSERT
WITH CHECK (true);
