-- Таблица Клиентов (CRM)
CREATE TABLE IF NOT EXISTS public.clients (
    user_id text PRIMARY KEY,
    name text,
    phone text,
    first_order timestamp with time zone DEFAULT now(),
    last_order timestamp with time zone DEFAULT now(),
    total_orders integer DEFAULT 1
);

-- Таблица Заказов
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text REFERENCES public.clients(user_id),
    customer_name text,
    customer_phone text,
    customer_address text,
    customer_payment text,
    customer_comment text,
    items jsonb, -- Храним массив товаров как JSON
    total numeric,
    status text DEFAULT 'Новый',
    created_at timestamp with time zone DEFAULT now()
);

-- Отключаем Row Level Security для простоты (или настройте политики, если нужно)
-- В данном случае мы пишем с сервера (Service Role), так что RLS нам не помешает, но для чтения с клиента может понадобиться
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Создаем политику на чтение (чтобы клиент мог видеть свои заказы, если мы будем читать напрямую)
create policy "Public clients are viewable by everyone"
  on public.clients for select
  using ( true );

create policy "Public orders are viewable by everyone"
  on public.orders for select
  using ( true );

-- Политика на вставку/обновление только с сервисным ключом (который у нас в Code.js)
-- (По умолчанию, если RLS включен и нет policy, доступ запрещен всем, кроме service_role, что нам и нужно для записи)
